version: '3.4'
services:
  frontend:
    stdin_open: true
    build:
      context: .
      target: development
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public
    ports:
      - $PORT:$PORT
    env_file:
      - .env